In [1]:
import numpy as np 
import pandas as pd 
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
train_data = pd.read_csv(r"Data\train_data_binned.csv")
test_data = pd.read_csv(r"Data\test_data_binned.csv")

In [5]:
train_data

,Unnamed: 0.1,Unnamed: 0,id,Feature 1,Feature 2,Feature 3,Feature 4,Feature 5,Feature 6,Feature 7,...,Feature 19,Feature 20,Feature 21,Feature 22,Feature 23,Feature 24,Feature 25,Feature 26,price,bin
0,0,143728,143728,0.53,0,0,1,0,0,0,...,1,0,0,62.0,56.0,5.16,5.20,3.21,1656,2
1,1,52657,52657,0.50,0,1,0,0,0,0,...,0,0,0,63.8,56.0,4.89,5.02,3.18,1063,1
2,2,124407,124407,2.03,0,0,1,0,0,0,...,0,0,0,59.2,60.0,8.39,8.29,4.94,18508,3
3,3,45535,45535,0.33,0,0,1,0,0,0,...,1,0,0,61.5,55.0,4.41,4.47,2.73,723,1
4,4,178894,178894,0.90,0,1,0,0,0,0,...,1,0,0,63.6,59.0,6.04,6.08,3.86,3187,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135496,135496,34345,34345,0.70,0,1,0,0,0,1,...,0,0,0,63.3,57.0,5.65,5.61,3.56,2380,2
135497,135497,9899,9899,0.33,0,0,1,0,0,0,...,0,0,0,62.6,57.0,4.43,4.40,2.77,693,1
135498,135498,142454,142454,2.03,0,0,0,1,0,0,...,1,0,0,59.7,59.0,8.38,8.30,4.97,16068,3
135499,135499,129168,129168,0.73,0,1,0,0,0,0,...,1,0,0,63.2,59.0,5.67,5.72,3.61,2964,2
135500,135500,10470,10470,1.72,0,0,1,0,0,0,...,0,0,0,61.2,57.0,7.67,7.72,4.71,15847,3

In [7]:
col = list(train_data.columns)
col.remove('Unnamed: 0')
col.remove('Unnamed: 0.1')
col.remove('id')
col.remove('price')
col.remove('bin')
col

['Feature 1',
 'Feature 2',
 'Feature 3',
 'Feature 4',
 'Feature 5',
 'Feature 6',
 'Feature 7',
 'Feature 8',
 'Feature 9',
 'Feature 10',
 'Feature 11',
 'Feature 12',
 'Feature 13',
 'Feature 14',
 'Feature 15',
 'Feature 16',
 'Feature 17',
 'Feature 18',
 'Feature 19',
 'Feature 20',
 'Feature 21',
 'Feature 22',
 'Feature 23',
 'Feature  24',
 'Feature 25',
 'Feature 26']

In [8]:
rf = RandomForestRegressor(n_estimators = 50, max_features = 0.8 , max_depth = 15, random_state = 18)

In [18]:
train_data_bin_1 = train_data.loc[train_data['bin'] == 1]
train_data_bin_1_input = train_data_bin_1[col]
train_data_bin_1_target = train_data_bin_1['price']

In [23]:
test_data_bin_1 = test_data.loc[test_data['bin'] == 1]
test_data_bin_1_input = test_data_bin_1[col]

In [27]:
test_data_bin_1_input

,Feature 1,Feature 2,Feature 3,Feature 4,Feature 5,Feature 6,Feature 7,Feature 8,Feature 9,Feature 10,...,Feature 17,Feature 18,Feature 19,Feature 20,Feature 21,Feature 22,Feature 23,Feature 24,Feature 25,Feature 26
3,0.30,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,62.9,58.0,4.26,4.30,2.69
4,0.23,0,0,0,1,0,0,1,0,0,...,0,0,0,0,1,62.4,58.0,3.96,3.98,2.47
5,0.30,0,0,1,0,0,0,0,0,1,...,0,1,0,0,0,61.6,57.0,4.32,4.30,2.65
8,0.42,0,0,1,0,0,1,0,0,0,...,0,0,1,0,0,61.9,56.0,4.81,4.78,2.97
11,0.32,0,0,0,1,0,1,0,0,0,...,0,0,0,0,0,61.4,59.0,4.37,4.43,2.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58051,0.42,0,0,0,0,1,1,0,0,0,...,0,0,0,0,0,61.1,56.0,4.82,4.86,2.95
58053,0.30,0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,61.6,57.0,4.30,4.33,2.66
58056,0.32,0,0,1,0,0,0,1,0,0,...,0,0,1,0,0,61.1,56.0,4.44,4.39,2.70
58060,0.31,0,0,1,0,0,0,1,0,0,...,0,1,0,0,0,61.5,55.0,4.39,4.36,2.69
58063,0.30,0,0,1,0,0,0,0,0,1,...,0,0,0,0,1,62.2,56.0,4.27,4.29,2.66

In [28]:
rf.fit(train_data_bin_1_input,train_data_bin_1_target)

RandomForestRegressor(max_depth=15, max_features=0.8, n_estimators=50,
                      random_state=18)

In [29]:
test_pred_bin_1 = rf.predict(test_data_bin_1_input)

In [31]:
price_pred_bin_1 = pd.DataFrame({'id': test_data_bin_1.id, 'Price': test_pred_bin_1})

In [38]:
train_data_bin_2 = train_data.loc[train_data['bin'] == 2]
train_data_bin_2_input = train_data_bin_2[col]
train_data_bin_2_target = train_data_bin_2['price']

In [39]:
test_data_bin_2 = test_data.loc[test_data['bin'] == 2]
test_data_bin_2_input = test_data_bin_2[col]

In [40]:
train_data_bin_2_input

,Feature 1,Feature 2,Feature 3,Feature 4,Feature 5,Feature 6,Feature 7,Feature 8,Feature 9,Feature 10,...,Feature 17,Feature 18,Feature 19,Feature 20,Feature 21,Feature 22,Feature 23,Feature 24,Feature 25,Feature 26
0,0.53,0,0,1,0,0,0,1,0,0,...,0,0,1,0,0,62.0,56.0,5.16,5.20,3.21
4,0.90,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,63.6,59.0,6.04,6.08,3.86
6,1.00,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,60.3,59.0,6.44,6.51,3.89
7,0.71,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,63.2,58.0,5.72,5.66,3.60
11,0.58,0,0,0,0,1,1,0,0,0,...,0,0,1,0,0,62.9,54.0,5.32,5.36,3.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135492,0.71,0,0,1,0,0,0,0,0,0,...,0,0,1,0,0,61.0,57.0,5.76,5.81,3.54
135493,0.70,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,60.5,58.0,5.78,5.74,3.48
135495,0.70,0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,62.0,56.0,5.64,5.74,3.53
135496,0.70,0,1,0,0,0,1,0,0,0,...,1,0,0,0,0,63.3,57.0,5.65,5.61,3.56
135499,0.73,0,1,0,0,0,0,1,0,0,...,0,0,1,0,0,63.2,59.0,5.67,5.72,3.61

In [41]:
rf.fit(train_data_bin_2_input,train_data_bin_2_target)

RandomForestRegressor(max_depth=15, max_features=0.8, n_estimators=50,
                      random_state=18)

In [42]:
test_pred_bin_2 = rf.predict(test_data_bin_2_input)

In [43]:
price_pred_bin_2 = pd.DataFrame({'id': test_data_bin_2.id, 'Price': test_pred_bin_2})

In [44]:
price_pred_bin_2

           id        Price
0      132523  3124.750718
1       70210  1399.552184
6      172800  2353.689727
13     147053  2575.734241
18      28064  2112.871884
...       ...          ...
58064   26736  2450.129640
58066   60718  1623.730827
58067   51474  4134.525091
58068   50296  2821.251378
58071  114675  2201.978162

[20116 rows x 2 columns]

In [45]:
train_data_bin_3 = train_data.loc[train_data['bin'] == 3]
train_data_bin_3_input = train_data_bin_3[col]
train_data_bin_3_target = train_data_bin_3['price']

In [46]:
test_data_bin_3 = test_data.loc[test_data['bin'] == 3]
test_data_bin_3_input = test_data_bin_3[col]

In [47]:
train_data_bin_3_input

,Feature 1,Feature 2,Feature 3,Feature 4,Feature 5,Feature 6,Feature 7,Feature 8,Feature 9,Feature 10,...,Feature 17,Feature 18,Feature 19,Feature 20,Feature 21,Feature 22,Feature 23,Feature 24,Feature 25,Feature 26
2,2.03,0,0,1,0,0,0,0,0,1,...,1,0,0,0,0,59.2,60.0,8.39,8.29,4.94
5,1.39,0,0,1,0,0,0,0,0,1,...,0,0,0,0,1,61.4,56.0,7.23,7.18,4.43
14,1.00,0,0,0,0,1,0,1,0,0,...,0,1,0,0,0,59.4,59.0,6.47,6.53,3.87
16,1.07,0,0,0,0,1,0,1,0,0,...,1,0,0,0,0,62.8,57.0,6.53,6.49,4.08
23,1.33,0,0,0,0,1,0,0,0,1,...,0,1,0,0,0,62.7,58.0,6.96,7.03,4.38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135476,1.59,0,0,0,1,0,0,0,1,0,...,0,0,0,0,0,62.3,59.0,7.48,7.45,4.65
135486,2.02,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,62.7,56.0,8.07,8.00,5.03
135491,1.11,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,63.0,58.0,6.64,6.68,4.21
135498,2.03,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,59.7,59.0,8.38,8.30,4.97
135500,1.72,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,61.2,57.0,7.67,7.72,4.71

In [48]:
rf.fit(train_data_bin_3_input,train_data_bin_3_target)

RandomForestRegressor(max_depth=15, max_features=0.8, n_estimators=50,
                      random_state=18)

In [49]:
test_pred_bin_3 = rf.predict(test_data_bin_3_input)

In [50]:
price_pred_bin_3 = pd.DataFrame({'id': test_data_bin_3.id, 'Price': test_pred_bin_3})

In [51]:
price_pred_bin_3

           id         Price
2       93051   4801.170653
7      156638   5945.289699
9      189119   8257.602892
10      67623   5325.765707
12      12900  13281.617753
...       ...           ...
58059  161591   6083.929324
58062  179890  10839.641385
58065   72852   8848.310694
58069   95077   5133.231671
58070   71500   6263.532122

[18503 rows x 2 columns]

In [52]:
temp = pd.concat([price_pred_bin_1,price_pred_bin_2])

In [54]:
final = pd.concat([temp,price_pred_bin_3])

In [55]:
final

           id         Price
3       67325    681.333964
4      189522    527.957618
5      129949    714.902527
8      148555   1014.539537
11      11370    634.177975
...       ...           ...
58059  161591   6083.929324
58062  179890  10839.641385
58065   72852   8848.310694
58069   95077   5133.231671
58070   71500   6263.532122

[58072 rows x 2 columns]

In [56]:
final.to_csv('./Results/Result10.csv')