In [172]:
import numpy as np 
import pandas as pd 
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import pickle

In [173]:
train_data_input = pd.read_csv(r'Data\traininput.csv')
targetvariable = pd.read_csv(r'Data\targetvariable.csv')

In [174]:
train_data_input

,Unnamed: 0,id,Feature 1,Feature 7,Feature 8,Feature 9,Feature 10,Feature 12,Feature 13,Feature 14,Feature 16,Feature 17,Feature 22,Feature 23,Feature 24,Feature 25,Feature 26
0,0,143728,0.100000,0,1,0,0,0,0,0,0,0,0.507692,0.233333,0.534715,0.519481,0.102556
1,1,52657,0.090909,0,0,0,0,0,1,0,1,0,0.600000,0.233333,0.506736,0.501499,0.101597
2,2,124407,0.554545,0,0,0,1,0,0,0,0,1,0.364103,0.366667,0.869430,0.828172,0.157827
3,3,45535,0.039394,0,1,0,0,0,0,0,0,0,0.482051,0.200000,0.456995,0.446553,0.087220
4,4,178894,0.212121,0,0,0,0,1,0,0,0,0,0.589744,0.333333,0.625907,0.607393,0.123323
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135496,135496,34345,0.151515,1,0,0,0,0,0,0,0,1,0.574359,0.266667,0.585492,0.560440,0.113738
135497,135497,9899,0.039394,0,0,0,0,1,0,0,0,0,0.538462,0.266667,0.459067,0.439560,0.088498
135498,135498,142454,0.554545,0,0,0,0,1,0,0,0,0,0.389744,0.333333,0.868394,0.829171,0.158786
135499,135499,129168,0.160606,0,1,0,0,0,0,0,0,0,0.569231,0.333333,0.587565,0.571429,0.115335
135500,135500,10470,0.460606,0,1,0,0,0,0,0,1,0,0.466667,0.266667,0.794819,0.771229,0.150479

In [175]:
train_data_input = train_data_input.drop('Unnamed: 0',axis = 1)
targetvariable = targetvariable.drop('Unnamed: 0',axis = 1)

In [176]:
train_data_input

,id,Feature 1,Feature 7,Feature 8,Feature 9,Feature 10,Feature 12,Feature 13,Feature 14,Feature 16,Feature 17,Feature 22,Feature 23,Feature 24,Feature 25,Feature 26
0,143728,0.100000,0,1,0,0,0,0,0,0,0,0.507692,0.233333,0.534715,0.519481,0.102556
1,52657,0.090909,0,0,0,0,0,1,0,1,0,0.600000,0.233333,0.506736,0.501499,0.101597
2,124407,0.554545,0,0,0,1,0,0,0,0,1,0.364103,0.366667,0.869430,0.828172,0.157827
3,45535,0.039394,0,1,0,0,0,0,0,0,0,0.482051,0.200000,0.456995,0.446553,0.087220
4,178894,0.212121,0,0,0,0,1,0,0,0,0,0.589744,0.333333,0.625907,0.607393,0.123323
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135496,34345,0.151515,1,0,0,0,0,0,0,0,1,0.574359,0.266667,0.585492,0.560440,0.113738
135497,9899,0.039394,0,0,0,0,1,0,0,0,0,0.538462,0.266667,0.459067,0.439560,0.088498
135498,142454,0.554545,0,0,0,0,1,0,0,0,0,0.389744,0.333333,0.868394,0.829171,0.158786
135499,129168,0.160606,0,1,0,0,0,0,0,0,0,0.569231,0.333333,0.587565,0.571429,0.115335
135500,10470,0.460606,0,1,0,0,0,0,0,1,0,0.466667,0.266667,0.794819,0.771229,0.150479

In [295]:
rf = RandomForestRegressor(n_estimators = 50, max_features = 0.8 , max_depth = 15, random_state = 18)

In [289]:
X_train ,X_test,y_train,y_test = train_test_split(train_data_input,targetvariable, test_size=0.2, random_state=42)

In [290]:
y_train

         price
91089    853.0
44923   9078.0
134431  4118.0
2180     787.0
45339   2617.0
...        ...
110268   906.0
119879   526.0
103694  9495.0
131932   756.0
121958  6906.0

[108400 rows x 1 columns]

In [291]:
rf.fit(X_train, y_train)

C:\Users\harsh\AppData\Local\Temp\ipykernel_5708\2725846524.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)

RandomForestRegressor(max_depth=20, max_features=0.8, n_estimators=50,
                      random_state=18)

In [292]:
y_pred = rf.predict(X_test)

In [293]:
with_burata = {}

with_burata['Mean Absolute Error:'] =  metrics.mean_absolute_error(y_test, y_pred)  
with_burata['Mean Squared Error:'] =  metrics.mean_squared_error(y_test, y_pred) 
with_burata['Root Mean Squared Error:'] = np.sqrt(metrics.mean_squared_error(y_test, y_pred))

In [294]:
with_burata

{'Mean Absolute Error:': 362.63837236390503,
 'Mean Squared Error:': 473451.71293673257,
 'Root Mean Squared Error:': 688.0782752977545}

In [296]:
rf.fit(train_data_input,targetvariable)

C:\Users\harsh\AppData\Local\Temp\ipykernel_5708\3203439712.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(train_data_input,targetvariable)

RandomForestRegressor(max_depth=15, max_features=0.8, n_estimators=50,
                      random_state=18)

In [297]:
test_data = pd.read_csv(r'Data\normalisedtest.csv')
test_data = test_data.drop('Unnamed: 0',axis = 1)

In [298]:
test_data

,id,Feature 1,Feature 7,Feature 8,Feature 9,Feature 10,Feature 12,Feature 13,Feature 14,Feature 16,Feature 17,Feature 22,Feature 23,Feature 24,Feature 25,Feature 26,price
0,132523,0.181818,0,0,1,0,0,0,0,1,0,0.410256,0.333333,0.625907,0.598402,0.115335,TBC
1,70210,0.109091,0,1,0,0,0,0,0,0,1,0.512821,0.166667,0.550259,0.527473,0.104792,TBC
2,93051,0.245455,0,0,0,0,0,0,0,1,0,0.487179,0.433333,0.663212,0.634366,0.125240,TBC
3,67325,0.030303,0,0,0,0,0,0,0,0,0,0.553846,0.300000,0.441451,0.429570,0.085942,TBC
4,189522,0.009091,0,1,0,0,0,0,0,0,0,0.528205,0.300000,0.410363,0.397602,0.078914,TBC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58067,51474,0.242424,1,0,0,0,0,0,0,0,1,0.497436,0.233333,0.656995,0.647353,0.126518,TBC
58068,50296,0.160606,0,1,0,0,0,0,0,1,0,0.512821,0.266667,0.594819,0.576424,0.114377,TBC
58069,95077,0.272727,0,0,0,0,0,0,0,1,0,0.517949,0.300000,0.682902,0.653347,0.130351,TBC
58070,71500,0.215152,0,1,0,0,0,0,0,0,0,0.302564,0.366667,0.665285,0.634366,0.118530,TBC
58071,114675,0.154545,0,0,1,0,0,0,0,0,1,0.435897,0.233333,0.594819,0.576424,0.111502,TBC

In [299]:
test_data_input = test_data.drop('price',axis = 1)

In [300]:
price_pred = rf.predict(test_data_input)

In [301]:
price_pred = pd.DataFrame({'id': test_data.id, 'Price': price_pred})

In [248]:
price_pred.to_csv('./Results/Result9.csv')