In [62]:
import numpy as np 
import pandas as pd 
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns

In [63]:
train_data = pd.read_csv(r"Data\train_data3.csv")
test_data = pd.read_csv(r"Data\test_data3.csv")

In [64]:
train_data.min()

Unnamed: 0         0.000000
id                 0.000000
Feature 1          0.200000
Feature 2          0.000000
Feature 3          0.000000
Feature 4          0.000000
Feature 5          0.000000
Feature 6          0.000000
Feature 7          0.000000
Feature 8          0.000000
Feature 9          0.000000
Feature 10         0.000000
Feature 11         0.000000
Feature 12         0.000000
Feature 13         0.000000
Feature 14         0.000000
Feature 15         0.000000
Feature 16         0.000000
Feature 17         0.000000
Feature 18         0.000000
Feature 19         0.000000
Feature 20         0.000000
Feature 21         0.000000
Feature 22        52.700000
Feature 23        51.000000
Feature  24        0.000000
Feature 25         0.000000
Feature 26         0.000000
price            326.000000
price2           938.095238
price3          1715.594864
Feature 26.1       0.000000
Feature 24.1       0.000000
Feature 25.1       0.000000
dtype: float64

In [65]:
train_data

,Unnamed: 0,id,Feature 1,Feature 2,Feature 3,Feature 4,Feature 5,Feature 6,Feature 7,Feature 8,...,Feature 23,Feature 24,Feature 25,Feature 26,price,price2,price3,Feature 26.1,Feature 24.1,Feature 25.1
0,143728,143728,0.53,0,0,1,0,0,0,1,...,56.0,5.16,5.20,3.21,1656,3124.528302,5895.336419,6.056604,9.735849,9.811321
1,52657,52657,0.50,0,1,0,0,0,0,0,...,56.0,4.89,5.02,3.18,1063,2126.000000,4252.000000,6.360000,9.780000,10.040000
2,124407,124407,2.03,0,0,1,0,0,0,0,...,60.0,8.39,8.29,4.94,18508,9117.241379,4491.251911,2.433498,4.133005,4.083744
3,45535,45535,0.33,0,0,1,0,0,0,1,...,55.0,4.41,4.47,2.73,723,2190.909091,6639.118457,8.272727,13.363636,13.545455
4,178894,178894,0.90,0,1,0,0,0,0,0,...,59.0,6.04,6.08,3.86,3187,3541.111111,3934.567901,4.288889,6.711111,6.755556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135354,34345,34345,0.70,0,1,0,0,0,1,0,...,57.0,5.65,5.61,3.56,2380,3400.000000,4857.142857,5.085714,8.071429,8.014286
135355,9899,9899,0.33,0,0,1,0,0,0,0,...,57.0,4.43,4.40,2.77,693,2100.000000,6363.636364,8.393939,13.424242,13.333333
135356,142454,142454,2.03,0,0,0,1,0,0,0,...,59.0,8.38,8.30,4.97,16068,7915.270936,3899.148244,2.448276,4.128079,4.088670
135357,129168,129168,0.73,0,1,0,0,0,0,1,...,59.0,5.67,5.72,3.61,2964,4060.273973,5562.019141,4.945205,7.767123,7.835616
135358,10470,10470,1.72,0,0,1,0,0,0,1,...,57.0,7.67,7.72,4.71,15847,9213.372093,5356.611682,2.738372,4.459302,4.488372

In [66]:
col = list(train_data.columns)
col.remove('Unnamed: 0')
#col.remove('Unnamed: 0.1')
#col.remove('Unnamed: 0.2')
col.remove('id')
col.remove('price')
col.remove('price2')
col.remove('price3')
#col.remove('bin')
#col.remove('Feature 2')
#col.remove('Feature 3')
#col.remove('Feature 4')
#col.remove('Feature 5')
#col.remove('Feature 6')
#col.remove('Feature 11')
#col.remove('Feature 15')
#col.remove('Feature 18')
#col.remove('Feature 19')
#col.remove('Feature 20')
#col.remove('Feature 21')
col

['Feature 1',
 'Feature 2',
 'Feature 3',
 'Feature 4',
 'Feature 5',
 'Feature 6',
 'Feature 7',
 'Feature 8',
 'Feature 9',
 'Feature 10',
 'Feature 11',
 'Feature 12',
 'Feature 13',
 'Feature 14',
 'Feature 15',
 'Feature 16',
 'Feature 17',
 'Feature 18',
 'Feature 19',
 'Feature 20',
 'Feature 21',
 'Feature 22',
 'Feature 23',
 'Feature  24',
 'Feature 25',
 'Feature 26',
 'Feature 26.1',
 'Feature 24.1',
 'Feature 25.1']

In [67]:
train_data['train-test'] = "train"
test_data['train-test'] = "test"

In [68]:
combined_df = pd.concat([train_data,test_data]).fillna('TBC')

In [69]:
scaler = MinMaxScaler()

#combined_df["Feature 1"] = scaler.fit_transform(np.array(combined_df["Feature 1"]).reshape(-1,1))
combined_df["Feature 22"] = scaler.fit_transform(np.array(combined_df["Feature 22"]).reshape(-1,1))
combined_df["Feature 23"] = scaler.fit_transform(np.array(combined_df["Feature 23"]).reshape(-1,1))
combined_df["Feature  24"] = scaler.fit_transform(np.array(combined_df["Feature  24"]).reshape(-1,1))
combined_df["Feature 25"] = scaler.fit_transform(np.array(combined_df["Feature 25"]).reshape(-1,1))
combined_df["Feature 26"] = scaler.fit_transform(np.array(combined_df["Feature 26"]).reshape(-1,1))
combined_df["Feature 24.1"] = scaler.fit_transform(np.array(combined_df["Feature  24"]).reshape(-1,1))
combined_df["Feature 25.1"] = scaler.fit_transform(np.array(combined_df["Feature 25"]).reshape(-1,1))
combined_df["Feature 26.1"] = scaler.fit_transform(np.array(combined_df["Feature 26"]).reshape(-1,1))

In [70]:
df_group = combined_df.groupby(['train-test'])
train_data = df_group.get_group('train')
test_data = df_group.get_group('test')

In [71]:
train_data.min()

Unnamed: 0                0
id                        0
Feature 1               0.2
Feature 2                 0
Feature 3                 0
Feature 4                 0
Feature 5                 0
Feature 6                 0
Feature 7                 0
Feature 8                 0
Feature 9                 0
Feature 10                0
Feature 11                0
Feature 12                0
Feature 13                0
Feature 14                0
Feature 15                0
Feature 16                0
Feature 17                0
Feature 18                0
Feature 19                0
Feature 20                0
Feature 21                0
Feature 22         0.030769
Feature 23         0.066667
Feature  24             0.0
Feature 25              0.0
Feature 26              0.0
price                 326.0
price2           938.095238
price3          1715.594864
Feature 26.1            0.0
Feature 24.1            0.0
Feature 25.1            0.0
train-test            train
dtype: object

In [72]:
train_data = train_data.drop('train-test',axis=1)
test_data = test_data.drop('train-test',axis=1)

In [73]:
test_data = test_data.drop('price',axis = 1)

In [74]:
test_data

,Unnamed: 0,id,Feature 1,Feature 2,Feature 3,Feature 4,Feature 5,Feature 6,Feature 7,Feature 8,...,Feature 22,Feature 23,Feature 24,Feature 25,Feature 26,price2,price3,Feature 26.1,Feature 24.1,Feature 25.1
0,132523,132523,0.80,0,0,0,1,0,0,0,...,0.410256,0.333333,0.635121,0.598402,0.115335,TBC,TBC,0.115335,0.635121,0.598402
1,70210,70210,0.56,0,0,1,0,0,0,1,...,0.512821,0.166667,0.558360,0.527473,0.104792,TBC,TBC,0.104792,0.558360,0.527473
2,93051,93051,1.01,0,0,0,1,0,0,0,...,0.487179,0.433333,0.672976,0.634366,0.125240,TBC,TBC,0.125240,0.672976,0.634366
3,67325,67325,0.30,0,0,0,0,1,0,0,...,0.553846,0.300000,0.447950,0.429570,0.085942,TBC,TBC,0.085942,0.447950,0.429570
4,189522,189522,0.23,0,0,0,1,0,0,1,...,0.528205,0.300000,0.416404,0.397602,0.078914,TBC,TBC,0.078914,0.416404,0.397602
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58067,51474,51474,1.00,0,0,1,0,0,1,0,...,0.497436,0.233333,0.666667,0.647353,0.126518,TBC,TBC,0.126518,0.666667,0.647353
58068,50296,50296,0.73,0,0,1,0,0,0,1,...,0.512821,0.266667,0.603575,0.576424,0.114377,TBC,TBC,0.114377,0.603575,0.576424
58069,95077,95077,1.10,0,0,0,1,0,0,0,...,0.517949,0.300000,0.692955,0.653347,0.130351,TBC,TBC,0.130351,0.692955,0.653347
58070,71500,71500,0.91,0,0,0,1,0,0,1,...,0.302564,0.366667,0.675079,0.634366,0.118530,TBC,TBC,0.118530,0.675079,0.634366
58071,114675,114675,0.71,0,0,1,0,0,0,0,...,0.435897,0.233333,0.603575,0.576424,0.111502,TBC,TBC,0.111502,0.603575,0.576424

In [75]:
from xgboost import XGBRegressor

In [76]:
xg = XGBRegressor(n_estimators=300, learning_rate=0.05,subsample = 0.75)

In [77]:
#train_data_bin_1 = train_data.loc[train_data['bin'] == 1]
train_data_input = train_data[col]
train_data_target = train_data['price2']

In [78]:
train_data_input

,Feature 1,Feature 2,Feature 3,Feature 4,Feature 5,Feature 6,Feature 7,Feature 8,Feature 9,Feature 10,...,Feature 20,Feature 21,Feature 22,Feature 23,Feature 24,Feature 25,Feature 26,Feature 26.1,Feature 24.1,Feature 25.1
0,0.53,0,0,1,0,0,0,1,0,0,...,0,0,0.507692,0.233333,0.542587,0.519481,0.102556,0.102556,0.542587,0.519481
1,0.50,0,1,0,0,0,0,0,0,0,...,0,0,0.600000,0.233333,0.514196,0.501499,0.101597,0.101597,0.514196,0.501499
2,2.03,0,0,1,0,0,0,0,0,1,...,0,0,0.364103,0.366667,0.882229,0.828172,0.157827,0.157827,0.882229,0.828172
3,0.33,0,0,1,0,0,0,1,0,0,...,0,0,0.482051,0.200000,0.463722,0.446553,0.087220,0.087220,0.463722,0.446553
4,0.90,0,1,0,0,0,0,0,0,0,...,0,0,0.589744,0.333333,0.635121,0.607393,0.123323,0.123323,0.635121,0.607393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135354,0.70,0,1,0,0,0,1,0,0,0,...,0,0,0.574359,0.266667,0.594111,0.560440,0.113738,0.113738,0.594111,0.560440
135355,0.33,0,0,1,0,0,0,0,0,0,...,0,0,0.538462,0.266667,0.465825,0.439560,0.088498,0.088498,0.465825,0.439560
135356,2.03,0,0,0,1,0,0,0,0,0,...,0,0,0.389744,0.333333,0.881178,0.829171,0.158786,0.158786,0.881178,0.829171
135357,0.73,0,1,0,0,0,0,1,0,0,...,0,0,0.569231,0.333333,0.596215,0.571429,0.115335,0.115335,0.596215,0.571429
135358,1.72,0,0,1,0,0,0,1,0,0,...,0,0,0.466667,0.266667,0.806519,0.771229,0.150479,0.150479,0.806519,0.771229

In [79]:
X_train ,X_test,y_train,y_test = train_test_split(train_data_input,train_data_target, test_size=0.2, random_state=42)

In [80]:
X_train.min()

Feature 1       0.200000
Feature 2       0.000000
Feature 3       0.000000
Feature 4       0.000000
Feature 5       0.000000
Feature 6       0.000000
Feature 7       0.000000
Feature 8       0.000000
Feature 9       0.000000
Feature 10      0.000000
Feature 11      0.000000
Feature 12      0.000000
Feature 13      0.000000
Feature 14      0.000000
Feature 15      0.000000
Feature 16      0.000000
Feature 17      0.000000
Feature 18      0.000000
Feature 19      0.000000
Feature 20      0.000000
Feature 21      0.000000
Feature 22      0.051282
Feature 23      0.066667
Feature  24     0.000000
Feature 25      0.000000
Feature 26      0.000000
Feature 26.1    0.000000
Feature 24.1    0.000000
Feature 25.1    0.000000
dtype: float64

In [81]:
xg.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.05, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=300, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [82]:
y_pred = xg.predict(X_test)

In [83]:
temp = X_test['Feature 1']
y_pred =  y_pred * temp.apply(lambda x : x) 
y_test =  y_test * temp.apply(lambda x : x)

In [84]:
X_test

,Feature 1,Feature 2,Feature 3,Feature 4,Feature 5,Feature 6,Feature 7,Feature 8,Feature 9,Feature 10,...,Feature 20,Feature 21,Feature 22,Feature 23,Feature 24,Feature 25,Feature 26,Feature 26.1,Feature 24.1,Feature 25.1
113522,0.90,0,1,0,0,0,1,0,0,0,...,0,0,0.605128,0.300000,0.633018,0.611389,0.123962,0.123962,0.633018,0.611389
132317,1.01,0,0,0,0,1,0,0,0,0,...,0,0,0.517949,0.300000,0.668770,0.636364,0.126518,0.126518,0.668770,0.636364
33331,0.36,0,0,1,0,0,0,0,0,0,...,0,0,0.497436,0.200000,0.480547,0.458541,0.090735,0.090735,0.480547,0.458541
46130,0.33,0,0,1,0,0,0,0,0,0,...,0,0,0.420513,0.233333,0.474238,0.448551,0.086901,0.086901,0.474238,0.448551
131917,0.30,0,0,0,0,1,0,1,0,0,...,0,0,0.553846,0.300000,0.443743,0.426573,0.085304,0.085304,0.443743,0.426573
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28991,0.71,0,0,0,0,1,0,0,0,0,...,0,0,0.461538,0.266667,0.597266,0.572428,0.111502,0.111502,0.597266,0.572428
87487,0.31,0,0,1,0,0,0,0,0,0,...,0,0,0.482051,0.266667,0.459516,0.432567,0.085623,0.085623,0.459516,0.432567
4420,2.04,0,0,0,1,0,0,0,0,0,...,0,0,0.476923,0.300000,0.854890,0.816184,0.159744,0.159744,0.854890,0.816184
132205,0.35,0,0,0,0,1,0,0,0,0,...,0,0,0.584615,0.266667,0.471083,0.450549,0.091374,0.091374,0.471083,0.450549
124103,1.01,0,0,0,1,0,0,0,1,0,...,0,0,0.558974,0.300000,0.676130,0.638362,0.129073,0.129073,0.676130,0.638362

In [85]:
temp

113522    0.90
132317    1.01
33331     0.36
46130     0.33
131917    0.30
          ...
28991     0.71
87487     0.31
4420      2.04
132205    0.35
124103    1.01
Name: Feature 1, Length: 27072, dtype: float64

In [86]:
y_test

113522     3674.0
132317     4932.0
33331      1124.0
46130       627.0
131917      564.0
           ...
28991      2028.0
87487       523.0
4420      18172.0
132205      509.0
124103     4276.0
Length: 27072, dtype: object

In [87]:
y_pred

113522     3625.358203
132317     4575.073638
33331       976.386709
46130       681.112266
131917      549.559900
              ...
28991      2059.627664
87487       608.233585
4420      16657.473574
132205      502.675238
124103     5156.096357
Name: Feature 1, Length: 27072, dtype: float64

In [88]:
error = {}

error['Mean Absolute Error:'] =  metrics.mean_absolute_error(y_test, y_pred)  
error['Mean Squared Error:'] =  metrics.mean_squared_error(y_test, y_pred) 
error['Root Mean Squared Error:'] = np.sqrt(metrics.mean_squared_error(y_test, y_pred))

In [89]:
error

{'Mean Absolute Error:': 293.6999555696888,
 'Mean Squared Error:': 320997.64687265764,
 'Root Mean Squared Error:': 566.5665423166618}

In [90]:
xg = XGBRegressor(n_estimators=300, learning_rate=0.05,subsample = 0.75)

In [96]:
train_data_input = train_data[col]
train_data_target = train_data['price2']

In [92]:
test_data_input = test_data[col]
#train_data_target = train_data['price2']

In [98]:
xg.fit(train_data_input,train_data_target)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.05, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=300, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [99]:
y_pred = xg.predict(test_data_input)

In [100]:
temp = test_data_input['Feature 1']
y_pred =  y_pred * temp.apply(lambda x : x)

In [101]:
price_pred = pd.DataFrame({'id': test_data.id, 'Price': y_pred})

In [102]:
price_pred.to_csv('./Results/Result22_xg_norm_trainp2_newf.csv',index=False)