In [1]:
import numpy as np 
import pandas as pd 
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
train_data = pd.read_csv(r"Data\master2.csv")
test_data = pd.read_csv(r"Data\test_data3.csv")

In [3]:
train_data.min()

id                0.000000
Feature 1         0.200000
Feature 2         0.000000
Feature 3         0.000000
Feature 4         0.000000
Feature 5         0.000000
Feature 6         0.000000
Feature 7         0.000000
Feature 8         0.000000
Feature 9         0.000000
Feature 10        0.000000
Feature 11        0.000000
Feature 12        0.000000
Feature 13        0.000000
Feature 14        0.000000
Feature 15        0.000000
Feature 16        0.000000
Feature 17        0.000000
Feature 18        0.000000
Feature 19        0.000000
Feature 20        0.000000
Feature 21        0.000000
Feature 22       50.800000
Feature 23       49.000000
Feature  24       0.000000
Feature 25        0.000000
Feature 26        0.000000
price           326.000000
price2          938.095238
price3         1759.809750
dtype: float64

In [4]:
train_data

,id,Feature 1,Feature 2,Feature 3,Feature 4,Feature 5,Feature 6,Feature 7,Feature 8,Feature 9,...,Feature 20,Feature 21,Feature 22,Feature 23,Feature 24,Feature 25,Feature 26,price,price2,price3
0,143728,0.53,0,0,1,0,0,0,1,0,...,0,0,62.0,56.0,5.16,5.20,3.21,1656,3124.528302,5895.336419
1,52657,0.50,0,1,0,0,0,0,0,0,...,0,0,63.8,56.0,4.89,5.02,3.18,1063,2126.000000,4252.000000
2,124407,2.03,0,0,1,0,0,0,0,0,...,0,0,59.2,60.0,8.39,8.29,4.94,18508,9117.241379,4491.251911
3,45535,0.33,0,0,1,0,0,0,1,0,...,0,0,61.5,55.0,4.41,4.47,2.73,723,2190.909091,6639.118457
4,178894,0.90,0,1,0,0,0,0,0,0,...,0,0,63.6,59.0,6.04,6.08,3.86,3187,3541.111111,3934.567901
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161137,26963,1.11,0,0,0,1,0,0,0,0,...,0,0,62.3,58.0,6.61,6.52,4.09,5408,4872.072072,4389.254119
161138,26964,0.33,0,0,1,0,0,0,0,0,...,0,0,61.9,55.0,4.44,4.42,2.74,1114,3375.757576,10229.568411
161139,26965,0.51,0,0,0,1,0,0,1,0,...,0,0,61.7,58.0,5.12,5.15,3.17,1656,3247.058824,6366.782007
161140,26966,0.27,0,0,0,0,1,0,0,1,...,0,1,61.8,56.0,4.19,4.20,2.60,682,2525.925926,9355.281207
161141,26967,1.25,0,0,0,1,0,0,0,0,...,0,0,62.0,58.0,6.90,6.88,4.27,5166,4132.800000,3306.240000

In [5]:
col = list(train_data.columns)
#col.remove('Unnamed: 0')
#col.remove('Unnamed: 0.1')
#col.remove('Unnamed: 0.2')
col.remove('id')
col.remove('price')
col.remove('price2')
col.remove('price3')
#col.remove('bin')
#col.remove('Feature 2')
#col.remove('Feature 3')
#col.remove('Feature 4')
#col.remove('Feature 5')
#col.remove('Feature 6')
#col.remove('Feature 11')
#col.remove('Feature 15')
#col.remove('Feature 18')
#col.remove('Feature 19')
#col.remove('Feature 20')
#col.remove('Feature 21')
col

['Feature 1',
 'Feature 2',
 'Feature 3',
 'Feature 4',
 'Feature 5',
 'Feature 6',
 'Feature 7',
 'Feature 8',
 'Feature 9',
 'Feature 10',
 'Feature 11',
 'Feature 12',
 'Feature 13',
 'Feature 14',
 'Feature 15',
 'Feature 16',
 'Feature 17',
 'Feature 18',
 'Feature 19',
 'Feature 20',
 'Feature 21',
 'Feature 22',
 'Feature 23',
 'Feature  24',
 'Feature 25',
 'Feature 26']

In [6]:
train_data['train-test'] = "train"
test_data['train-test'] = "test"

In [7]:
combined_df = pd.concat([train_data,test_data]).fillna('TBC')

In [8]:
scaler = MinMaxScaler()

#combined_df["Feature 1"] = scaler.fit_transform(np.array(combined_df["Feature 1"]).reshape(-1,1))
combined_df["Feature 22"] = scaler.fit_transform(np.array(combined_df["Feature 22"]).reshape(-1,1))
combined_df["Feature 23"] = scaler.fit_transform(np.array(combined_df["Feature 23"]).reshape(-1,1))
combined_df["Feature  24"] = scaler.fit_transform(np.array(combined_df["Feature  24"]).reshape(-1,1))
combined_df["Feature 25"] = scaler.fit_transform(np.array(combined_df["Feature 25"]).reshape(-1,1))
combined_df["Feature 26"] = scaler.fit_transform(np.array(combined_df["Feature 26"]).reshape(-1,1))
#combined_df["Feature 24.1"] = scaler.fit_transform(np.array(combined_df["Feature  24"]).reshape(-1,1))
#combined_df["Feature 25.1"] = scaler.fit_transform(np.array(combined_df["Feature 25"]).reshape(-1,1))
#combined_df["Feature 26.1"] = scaler.fit_transform(np.array(combined_df["Feature 26"]).reshape(-1,1))

In [9]:
df_group = combined_df.groupby(['train-test'])
train_data = df_group.get_group('train')
test_data = df_group.get_group('test')

In [10]:
train_data.min()

id                       0
Feature 1              0.2
Feature 2                0
Feature 3                0
Feature 4                0
Feature 5                0
Feature 6                0
Feature 7                0
Feature 8                0
Feature 9                0
Feature 10               0
Feature 11               0
Feature 12               0
Feature 13               0
Feature 14               0
Feature 15               0
Feature 16               0
Feature 17               0
Feature 18               0
Feature 19               0
Feature 20               0
Feature 21               0
Feature 22             0.0
Feature 23             0.0
Feature  24            0.0
Feature 25             0.0
Feature 26             0.0
price                326.0
price2          938.095238
price3          1759.80975
train-test           train
Unnamed: 0             TBC
Feature 26.1           TBC
Feature 24.1           TBC
Feature 25.1           TBC
dtype: object

In [11]:
train_data = train_data.drop('train-test',axis=1)
test_data = test_data.drop('train-test',axis=1)

In [12]:
test_data = test_data.drop('price',axis = 1)

In [13]:
test_data

,id,Feature 1,Feature 2,Feature 3,Feature 4,Feature 5,Feature 6,Feature 7,Feature 8,Feature 9,...,Feature 23,Feature 24,Feature 25,Feature 26,price2,price3,Unnamed: 0,Feature 26.1,Feature 24.1,Feature 25.1
0,132523,0.80,0,0,0,1,0,0,0,1,...,0.333333,0.635121,0.101698,0.115335,TBC,TBC,132523.0,4.5125,7.55,7.4875
1,70210,0.56,0,0,1,0,0,0,1,0,...,0.166667,0.558360,0.089643,0.104792,TBC,TBC,70210.0,5.857143,9.482143,9.428571
2,93051,1.01,0,0,0,1,0,0,0,0,...,0.433333,0.672976,0.107810,0.125240,TBC,TBC,93051.0,3.881188,6.336634,6.287129
3,67325,0.30,0,0,0,0,1,0,0,0,...,0.300000,0.447950,0.073005,0.085942,TBC,TBC,67325.0,8.966667,14.2,14.333333
4,189522,0.23,0,0,0,1,0,0,1,0,...,0.300000,0.416404,0.067572,0.078914,TBC,TBC,189522.0,10.73913,17.217391,17.304348
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58067,51474,1.00,0,0,1,0,0,1,0,0,...,0.233333,0.666667,0.110017,0.126518,TBC,TBC,51474.0,3.96,6.34,6.48
58068,50296,0.73,0,0,1,0,0,0,1,0,...,0.266667,0.603575,0.097963,0.114377,TBC,TBC,50296.0,4.90411,7.863014,7.90411
58069,95077,1.10,0,0,0,1,0,0,0,0,...,0.300000,0.692955,0.111036,0.130351,TBC,TBC,95077.0,3.709091,5.990909,5.945455
58070,71500,0.91,0,0,0,1,0,0,1,0,...,0.366667,0.675079,0.107810,0.118530,TBC,TBC,71500.0,4.076923,7.054945,6.978022
58071,114675,0.71,0,0,1,0,0,0,0,1,...,0.233333,0.603575,0.097963,0.111502,TBC,TBC,114675.0,4.915493,8.084507,8.126761

In [14]:
from xgboost import XGBRegressor

In [15]:
xg = XGBRegressor(n_estimators=500, learning_rate=0.05,subsample = 0.9)

In [16]:
#train_data_bin_1 = train_data.loc[train_data['bin'] == 1]
train_data_input = train_data[col]
train_data_target = train_data['price2']

In [17]:
train_data_input

,Feature 1,Feature 2,Feature 3,Feature 4,Feature 5,Feature 6,Feature 7,Feature 8,Feature 9,Feature 10,...,Feature 17,Feature 18,Feature 19,Feature 20,Feature 21,Feature 22,Feature 23,Feature 24,Feature 25,Feature 26
0,0.53,0,0,1,0,0,0,1,0,0,...,0,0,1,0,0,0.491228,0.233333,0.542587,0.088285,0.102556
1,0.50,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0.570175,0.233333,0.514196,0.085229,0.101597
2,2.03,0,0,1,0,0,0,0,0,1,...,1,0,0,0,0,0.368421,0.366667,0.882229,0.140747,0.157827
3,0.33,0,0,1,0,0,0,1,0,0,...,0,0,1,0,0,0.469298,0.200000,0.463722,0.075891,0.087220
4,0.90,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0.561404,0.333333,0.635121,0.103226,0.123323
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161137,1.11,0,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0.504386,0.300000,0.695058,0.110696,0.130671
161138,0.33,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0.486842,0.200000,0.466877,0.075042,0.087540
161139,0.51,0,0,0,1,0,0,1,0,0,...,0,0,1,0,0,0.478070,0.300000,0.538381,0.087436,0.101278
161140,0.27,0,0,0,0,1,0,0,1,0,...,0,0,0,0,1,0.482456,0.233333,0.440589,0.071307,0.083067
161141,1.25,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0.491228,0.300000,0.725552,0.116808,0.136422

In [18]:
X_train ,X_test,y_train,y_test = train_test_split(train_data_input,train_data_target, test_size=0.2, random_state=42)

In [19]:
X_train.min()

Feature 1      0.2
Feature 2      0.0
Feature 3      0.0
Feature 4      0.0
Feature 5      0.0
Feature 6      0.0
Feature 7      0.0
Feature 8      0.0
Feature 9      0.0
Feature 10     0.0
Feature 11     0.0
Feature 12     0.0
Feature 13     0.0
Feature 14     0.0
Feature 15     0.0
Feature 16     0.0
Feature 17     0.0
Feature 18     0.0
Feature 19     0.0
Feature 20     0.0
Feature 21     0.0
Feature 22     0.0
Feature 23     0.0
Feature  24    0.0
Feature 25     0.0
Feature 26     0.0
dtype: float64

In [20]:
xg.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.05, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=500, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [21]:
y_pred = xg.predict(X_test)

In [22]:
temp = X_test['Feature 1']
y_pred =  y_pred * temp.apply(lambda x : x) 
y_test =  y_test * temp.apply(lambda x : x)

In [23]:
X_test

,Feature 1,Feature 2,Feature 3,Feature 4,Feature 5,Feature 6,Feature 7,Feature 8,Feature 9,Feature 10,...,Feature 17,Feature 18,Feature 19,Feature 20,Feature 21,Feature 22,Feature 23,Feature 24,Feature 25,Feature 26
125722,0.91,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0.578947,0.166667,0.639327,0.102547,0.124601
136029,0.70,0,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0.557018,0.233333,0.587802,0.095586,0.113738
18850,0.51,0,0,1,0,0,1,0,0,0,...,0,0,1,0,0,0.513158,0.266667,0.535226,0.087267,0.101917
9636,1.04,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0.508772,0.300000,0.682440,0.109677,0.129073
112227,0.30,0,0,1,0,0,1,0,0,0,...,0,0,0,0,1,0.526316,0.266667,0.449001,0.073005,0.085942
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152844,0.70,0,0,1,0,0,0,0,0,0,...,0,0,0,1,0,0.456140,0.266667,0.598318,0.097114,0.111502
142162,1.00,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0.486842,0.300000,0.662461,0.108149,0.125240
69437,0.33,0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0.442982,0.266667,0.471083,0.075552,0.086901
83075,0.30,0,0,1,0,0,1,0,0,0,...,0,0,1,0,0,0.495614,0.200000,0.455310,0.073854,0.085942
127773,0.40,0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0.491228,0.300000,0.493165,0.080136,0.093291

In [24]:
temp

125722    0.91
136029    0.70
18850     0.51
9636      1.04
112227    0.30
          ...
152844    0.70
142162    1.00
69437     0.33
83075     0.30
127773    0.40
Name: Feature 1, Length: 32229, dtype: float64

In [25]:
y_test

125722    3615.0
136029    1675.0
18850     1695.0
9636      4423.0
112227     662.0
           ...
152844    2947.0
142162    4953.0
69437     1124.0
83075      670.0
127773     807.0
Length: 32229, dtype: object

In [26]:
y_pred

125722    3695.672627
136029    1897.763403
18850     1778.901416
9636      4285.603867
112227     805.243066
             ...
152844    2943.401562
142162    4487.371094
69437     1021.877549
83075      745.616382
127773     766.403809
Name: Feature 1, Length: 32229, dtype: float64

In [27]:
error = {}

error['Mean Absolute Error:'] =  metrics.mean_absolute_error(y_test, y_pred)  
error['Mean Squared Error:'] =  metrics.mean_squared_error(y_test, y_pred) 
error['Root Mean Squared Error:'] = np.sqrt(metrics.mean_squared_error(y_test, y_pred))

In [28]:
error

{'Mean Absolute Error:': 285.9973353531351,
 'Mean Squared Error:': 308633.6376596431,
 'Root Mean Squared Error:': 555.5480516207784}

In [37]:
xg = XGBRegressor(n_estimators=300, learning_rate=0.05,subsample = 0.75)

In [38]:
train_data_input = train_data[col]
train_data_target = train_data['price2']

In [39]:
test_data_input = test_data[col]
#train_data_target = train_data['price2']

In [40]:
xg.fit(train_data_input,train_data_target)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.05, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=300, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [41]:
y_pred = xg.predict(test_data_input)

In [42]:
temp = test_data_input['Feature 1']
y_pred =  y_pred * temp.apply(lambda x : x)

In [43]:
price_pred = pd.DataFrame({'id': test_data.id, 'Price': y_pred})

In [36]:
price_pred.to_csv('./Results/Result24_xg_norm_trainp2_master2_1.csv',index=False)