In [1]:
import numpy as np 
import pandas as pd 
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
train_data = pd.read_csv(r"Data\train_data2.csv")
test_data = pd.read_csv(r"Data\test.csv")

In [3]:
train_data

,Unnamed: 0.1,Unnamed: 0,id,Feature 1,Feature 2,Feature 3,Feature 4,Feature 5,Feature 6,Feature 7,...,Feature 20,Feature 21,Feature 22,Feature 23,Feature 24,Feature 25,Feature 26,price,price2,price3
0,0,143728,143728,0.53,0,0,1,0,0,0,...,0,0,62.0,56.0,5.16,5.20,3.21,1656,3124.528302,5895.336419
1,1,52657,52657,0.50,0,1,0,0,0,0,...,0,0,63.8,56.0,4.89,5.02,3.18,1063,2126.000000,4252.000000
2,2,124407,124407,2.03,0,0,1,0,0,0,...,0,0,59.2,60.0,8.39,8.29,4.94,18508,9117.241379,4491.251911
3,3,45535,45535,0.33,0,0,1,0,0,0,...,0,0,61.5,55.0,4.41,4.47,2.73,723,2190.909091,6639.118457
4,4,178894,178894,0.90,0,1,0,0,0,0,...,0,0,63.6,59.0,6.04,6.08,3.86,3187,3541.111111,3934.567901
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135354,135496,34345,34345,0.70,0,1,0,0,0,1,...,0,0,63.3,57.0,5.65,5.61,3.56,2380,3400.000000,4857.142857
135355,135497,9899,9899,0.33,0,0,1,0,0,0,...,0,0,62.6,57.0,4.43,4.40,2.77,693,2100.000000,6363.636364
135356,135498,142454,142454,2.03,0,0,0,1,0,0,...,0,0,59.7,59.0,8.38,8.30,4.97,16068,7915.270936,3899.148244
135357,135499,129168,129168,0.73,0,1,0,0,0,0,...,0,0,63.2,59.0,5.67,5.72,3.61,2964,4060.273973,5562.019141
135358,135500,10470,10470,1.72,0,0,1,0,0,0,...,0,0,61.2,57.0,7.67,7.72,4.71,15847,9213.372093,5356.611682

In [4]:
col = list(train_data.columns)
col.remove('Unnamed: 0')
col.remove('Unnamed: 0.1')
col.remove('id')
col.remove('price')
col.remove('price3')
col.remove('price2')
col

['Feature 1',
 'Feature 2',
 'Feature 3',
 'Feature 4',
 'Feature 5',
 'Feature 6',
 'Feature 7',
 'Feature 8',
 'Feature 9',
 'Feature 10',
 'Feature 11',
 'Feature 12',
 'Feature 13',
 'Feature 14',
 'Feature 15',
 'Feature 16',
 'Feature 17',
 'Feature 18',
 'Feature 19',
 'Feature 20',
 'Feature 21',
 'Feature 22',
 'Feature 23',
 'Feature  24',
 'Feature 25',
 'Feature 26']

In [5]:
from xgboost import XGBRegressor

In [20]:
xg = XGBRegressor(n_estimators=300, learning_rate=0.05,subsample = 0.75)

In [21]:
train_data_input = train_data[col]
train_data_target = train_data['price2']

In [22]:
train_data_input

,Feature 1,Feature 2,Feature 3,Feature 4,Feature 5,Feature 6,Feature 7,Feature 8,Feature 9,Feature 10,...,Feature 17,Feature 18,Feature 19,Feature 20,Feature 21,Feature 22,Feature 23,Feature 24,Feature 25,Feature 26
0,0.53,0,0,1,0,0,0,1,0,0,...,0,0,1,0,0,62.0,56.0,5.16,5.20,3.21
1,0.50,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,63.8,56.0,4.89,5.02,3.18
2,2.03,0,0,1,0,0,0,0,0,1,...,1,0,0,0,0,59.2,60.0,8.39,8.29,4.94
3,0.33,0,0,1,0,0,0,1,0,0,...,0,0,1,0,0,61.5,55.0,4.41,4.47,2.73
4,0.90,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,63.6,59.0,6.04,6.08,3.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135354,0.70,0,1,0,0,0,1,0,0,0,...,1,0,0,0,0,63.3,57.0,5.65,5.61,3.56
135355,0.33,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,62.6,57.0,4.43,4.40,2.77
135356,2.03,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,59.7,59.0,8.38,8.30,4.97
135357,0.73,0,1,0,0,0,0,1,0,0,...,0,0,1,0,0,63.2,59.0,5.67,5.72,3.61
135358,1.72,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,61.2,57.0,7.67,7.72,4.71

In [23]:
train_data_target

0         3124.528302
1         2126.000000
2         9117.241379
3         2190.909091
4         3541.111111
             ...
135354    3400.000000
135355    2100.000000
135356    7915.270936
135357    4060.273973
135358    9213.372093
Name: price2, Length: 135359, dtype: float64

In [24]:
test_data_input = test_data[col]
test_temp = test_data['Feature 1']

In [25]:
test_data_input

,Feature 1,Feature 2,Feature 3,Feature 4,Feature 5,Feature 6,Feature 7,Feature 8,Feature 9,Feature 10,...,Feature 17,Feature 18,Feature 19,Feature 20,Feature 21,Feature 22,Feature 23,Feature 24,Feature 25,Feature 26
0,0.80,0,0,0,1,0,0,0,1,0,...,0,0,0,0,0,60.1,59.0,6.04,5.99,3.61
1,0.56,0,0,1,0,0,0,1,0,0,...,1,0,0,0,0,62.1,54.0,5.31,5.28,3.28
2,1.01,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,61.6,62.0,6.40,6.35,3.92
3,0.30,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,62.9,58.0,4.26,4.30,2.69
4,0.23,0,0,0,1,0,0,1,0,0,...,0,0,0,0,1,62.4,58.0,3.96,3.98,2.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58067,1.00,0,0,1,0,0,1,0,0,0,...,1,0,0,0,0,61.8,56.0,6.34,6.48,3.96
58068,0.73,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,62.1,57.0,5.74,5.77,3.58
58069,1.10,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,62.2,58.0,6.59,6.54,4.08
58070,0.91,0,0,0,1,0,0,1,0,0,...,0,1,0,0,0,58.0,60.0,6.42,6.35,3.71
58071,0.71,0,0,1,0,0,0,0,1,0,...,1,0,0,0,0,60.6,56.0,5.74,5.77,3.49

In [26]:
xg.fit(train_data_input,train_data_target)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.05, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=300, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [27]:
test_pred = xg.predict(test_data_input)

In [28]:
test_pred

array([3799.0503, 2364.6885, 4412.472 , ..., 4579.4185, 5964.786 ,
       3263.2402], dtype=float32)

In [29]:
test_pred_f = test_pred * test_temp.apply(lambda x : x)

In [30]:
test_pred_f

0        3039.240234
1        1324.225547
2        4456.596890
3         671.581201
4         554.812278
            ...
58067    4788.932617
58068    2851.862627
58069    5037.360303
58070    5427.955381
58071    2316.900566
Name: Feature 1, Length: 58072, dtype: float64

In [31]:
price_pred = pd.DataFrame({'id': test_data.id, 'Price': test_pred_f})

In [19]:
price_pred.to_csv('./Results/Result19_xg_F1.csv',index=False)