In [192]:
import numpy as np 
import pandas as pd 
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from boruta import BorutaPy

In [193]:
train_data = pd.read_csv(r"Data\train.csv")
test_data = pd.read_csv(r"Data\test.csv")

In [194]:
train_data = train_data.drop('Unnamed: 0',axis = 1)
test_data = test_data.drop('Unnamed: 0',axis = 1)

In [195]:
train_data['train-test'] = "train"
test_data['train-test'] = "test"

In [196]:
train_data.head().T

                  0      1       2      3       4
id           143728  52657  124407  45535  178894
Feature 1      0.53    0.5    2.03   0.33     0.9
Feature 2         0      0       0      0       0
Feature 3         0      1       0      0       1
Feature 4         1      0       1      1       0
Feature 5         0      0       0      0       0
Feature 6         0      0       0      0       0
Feature 7         0      0       0      0       0
Feature 8         1      0       0      1       0
Feature 9         0      0       0      0       0
Feature 10        0      0       1      0       0
Feature 11        0      0       0      0       0
Feature 12        0      0       0      0       1
Feature 13        0      1       0      0       0
Feature 14        0      0       0      0       0
Feature 15        0      0       0      0       0
Feature 16        0      1       0      0       0
Feature 17        0      0       1      0       0
Feature 18        0      0       0      0       0
Feature 19        1      0       0      1       1
Feature 20        0      0       0      0       0
Feature 21        0      0       0      0       0
Feature 22     62.0   63.8    59.2   61.5    63.6
Feature 23     56.0   56.0    60.0   55.0    59.0
Feature  24    5.16   4.89    8.39   4.41    6.04
Feature 25      5.2   5.02    8.29   4.47    6.08
Feature 26     3.21   3.18    4.94   2.73    3.86
price          1656   1063   18508    723    3187
train-test    train  train   train  train   train

In [197]:
test_data.head().T

                  0      1      2      3       4
id           132523  70210  93051  67325  189522
Feature 1       0.8   0.56   1.01    0.3    0.23
Feature 2         0      0      0      0       0
Feature 3         0      0      0      0       0
Feature 4         0      1      0      0       0
Feature 5         1      0      1      0       1
Feature 6         0      0      0      1       0
Feature 7         0      0      0      0       0
Feature 8         0      1      0      0       1
Feature 9         1      0      0      0       0
Feature 10        0      0      0      0       0
Feature 11        0      0      1      1       0
Feature 12        0      0      0      0       0
Feature 13        0      0      0      0       0
Feature 14        0      0      0      0       0
Feature 15        0      0      0      0       0
Feature 16        1      0      1      0       0
Feature 17        0      1      0      0       0
Feature 18        0      0      0      0       0
Feature 19        0      0      0      0       0
Feature 20        0      0      0      1       0
Feature 21        0      0      0      0       1
Feature 22     60.1   62.1   61.6   62.9    62.4
Feature 23     59.0   54.0   62.0   58.0    58.0
Feature  24    6.04   5.31    6.4   4.26    3.96
Feature 25     5.99   5.28   6.35    4.3    3.98
Feature 26     3.61   3.28   3.92   2.69    2.47
train-test     test   test   test   test    test

In [198]:
combined_df = pd.concat([train_data,test_data]).fillna('TBC')

In [199]:
combined_df.to_csv('./Data/CombinedData.csv')

In [200]:
scaler = MinMaxScaler()

combined_df["Feature 1"] = scaler.fit_transform(np.array(combined_df["Feature 1"]).reshape(-1,1))
combined_df["Feature 22"] = scaler.fit_transform(np.array(combined_df["Feature 22"]).reshape(-1,1))
combined_df["Feature 23"] = scaler.fit_transform(np.array(combined_df["Feature 23"]).reshape(-1,1))
combined_df["Feature  24"] = scaler.fit_transform(np.array(combined_df["Feature  24"]).reshape(-1,1))
combined_df["Feature 25"] = scaler.fit_transform(np.array(combined_df["Feature 25"]).reshape(-1,1))
combined_df["Feature 26"] = scaler.fit_transform(np.array(combined_df["Feature 26"]).reshape(-1,1))

In [201]:
combined_df.T

,0,1,2,3,4,5,6,7,8,9,...,58062,58063,58064,58065,58066,58067,58068,58069,58070,58071
id,143728,52657,124407,45535,178894,171041,166851,33219,40794,43937,...,179890,2581,26736,72852,60718,51474,50296,95077,71500,114675
Feature 1,0.1,0.090909,0.554545,0.039394,0.212121,0.360606,0.242424,0.154545,0.066667,0.045455,...,0.424242,0.030303,0.175758,0.393939,0.09697,0.242424,0.160606,0.272727,0.215152,0.154545
Feature 2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Feature 3,0,1,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
Feature 4,1,0,1,1,0,1,0,0,1,0,...,1,1,0,0,0,1,1,0,0,1
Feature 5,0,0,0,0,0,0,1,0,0,1,...,0,0,0,1,1,0,0,1,1,0
Feature 6,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
Feature 7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,0,0
Feature 8,1,0,0,1,0,0,0,1,1,0,...,0,0,0,0,0,0,1,0,1,0
Feature 9,0,0,0,0,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,0,1
Feature 10,0,0,1,0,0,1,0,0,0,1,...,0,1,0,0,0,0,0,0,0,0
Feature 11,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,1,0,0
Feature 12,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Feature 13,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Feature 14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Feature 15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Feature 16,0,1,0,0,0,0,1,1,0,0,...,1,0,0,0,1,0,1,1,0,0
Feature 17,0,0,1,0,0,0,0,0,0,0,...,0,0,1,1,0,1,0,0,0,1
Feature 18,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
Feature 19,1,0,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Feature 20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Feature 21,0,0,0,0,0,1,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
Feature 22,0.507692,0.6,0.364103,0.482051,0.589744,0.476923,0.420513,0.569231,0.451282,0.492308,...,0.502564,0.517949,0.6,0.466667,0.435897,0.497436,0.512821,0.517949,0.302564,0.435897
Feature 23,0.233333,0.233333,0.366667,0.2,0.333333,0.233333,0.333333,0.3,0.233333,0.333333,...,0.2,0.233333,0.266667,0.366667,0.366667,0.233333,0.266667,0.3,0.366667,0.233333
Feature 24,0.534715,0.506736,0.86943,0.456995,0.625907,0.749223,0.667358,0.592746,0.499482,0.46114,...,0.778238,0.442487,0.603109,0.759585,0.537824,0.656995,0.594819,0.682902,0.665285,0.594819
Feature 25,0.519481,0.501499,0.828172,0.446553,0.607393,0.717283,0.65035,0.565435,0.485514,0.445554,...,0.744256,0.428571,0.585415,0.737263,0.523477,0.647353,0.576424,0.653347,0.634366,0.576424
Feature 26,0.102556,0.101597,0.157827,0.08722,0.123323,0.141534,0.124281,0.115016,0.094249,0.08754,...,0.148243,0.084984,0.119169,0.144089,0.100958,0.126518,0.114377,0.130351,0.11853,0.111502
price,1656.0,1063.0,18508.0,723.0,3187.0,12401.0,3924.0,2702.0,1145.0,706.0,...,TBC,TBC,TBC,TBC,TBC,TBC,TBC,TBC,TBC,TBC
train-test,train,train,train,train,train,train,train,train,train,train,...,test,test,test,test,test,test,test,test,test,test

In [202]:
df_group = combined_df.groupby(['train-test'])
train_data = df_group.get_group('train')
test_data = df_group.get_group('test')

In [203]:
train_data = train_data.drop('train-test',axis=1)
test_data = test_data.drop('train-test',axis=1)

In [204]:
test_data

,id,Feature 1,Feature 2,Feature 3,Feature 4,Feature 5,Feature 6,Feature 7,Feature 8,Feature 9,...,Feature 18,Feature 19,Feature 20,Feature 21,Feature 22,Feature 23,Feature 24,Feature 25,Feature 26,price
0,132523,0.181818,0,0,0,1,0,0,0,1,...,0,0,0,0,0.410256,0.333333,0.625907,0.598402,0.115335,TBC
1,70210,0.109091,0,0,1,0,0,0,1,0,...,0,0,0,0,0.512821,0.166667,0.550259,0.527473,0.104792,TBC
2,93051,0.245455,0,0,0,1,0,0,0,0,...,0,0,0,0,0.487179,0.433333,0.663212,0.634366,0.125240,TBC
3,67325,0.030303,0,0,0,0,1,0,0,0,...,0,0,1,0,0.553846,0.300000,0.441451,0.429570,0.085942,TBC
4,189522,0.009091,0,0,0,1,0,0,1,0,...,0,0,0,1,0.528205,0.300000,0.410363,0.397602,0.078914,TBC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58067,51474,0.242424,0,0,1,0,0,1,0,0,...,0,0,0,0,0.497436,0.233333,0.656995,0.647353,0.126518,TBC
58068,50296,0.160606,0,0,1,0,0,0,1,0,...,0,0,0,0,0.512821,0.266667,0.594819,0.576424,0.114377,TBC
58069,95077,0.272727,0,0,0,1,0,0,0,0,...,0,0,0,0,0.517949,0.300000,0.682902,0.653347,0.130351,TBC
58070,71500,0.215152,0,0,0,1,0,0,1,0,...,1,0,0,0,0.302564,0.366667,0.665285,0.634366,0.118530,TBC
58071,114675,0.154545,0,0,1,0,0,0,0,1,...,0,0,0,0,0.435897,0.233333,0.594819,0.576424,0.111502,TBC

In [205]:
target_variable = train_data['price']
train_data_input = train_data.drop('price',axis = 1)

In [183]:
rf = RandomForestRegressor(n_estimators=100, max_depth=5, random_state=42)

# let's initialize Boruta
feat_selector = BorutaPy(
    verbose=2,
    estimator=rf,
    n_estimators='auto',
    max_iter=26  # number of iterations to perform
)

# train Boruta
# N.B.: X and y must be numpy arrays
feat_selector.fit(train_data_input.values.astype(float),target_variable.values.astype(int))

# print support and ranking for each feature
print("\n------Support and Ranking for each feature------")
for i in range(len(feat_selector.support_)):
    if feat_selector.support_[i]:
        print("Passes the test: ", train_data_input.columns[i],
              " - Ranking: ", feat_selector.ranking_[i])
    else:
        print("Doesn't pass the test: ",
              train_data_input.columns[i], " - Ranking: ", feat_selector.ranking_[i])

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [210]:
col = train_data_input.columns
a = len(train_data_input.columns)
for i in range(2,a):
    if (hits[i] == 0):
        print(col[i])
        train_data_input = train_data_input.drop(col[i],axis = 1)

Feature 2
Feature 3
Feature 4
Feature 5
Feature 6
Feature 11
Feature 15
Feature 18
Feature 19
Feature 20
Feature 21
Feature 23

In [206]:

train_data_input = train_data_input.drop('Feature 2',axis = 1)
train_data_input = train_data_input.drop('Feature 3',axis = 1)
train_data_input = train_data_input.drop('Feature 4',axis = 1)
train_data_input = train_data_input.drop('Feature 5',axis = 1)
train_data_input = train_data_input.drop('Feature 6',axis = 1)
train_data_input = train_data_input.drop('Feature 11',axis = 1)
train_data_input = train_data_input.drop('Feature 15',axis = 1)
train_data_input = train_data_input.drop('Feature 18',axis = 1)
train_data_input = train_data_input.drop('Feature 19',axis = 1)
train_data_input = train_data_input.drop('Feature 20',axis = 1)
train_data_input = train_data_input.drop('Feature 21',axis = 1)
#train_data_input = train_data_input.drop('Feature 23',axis = 1)

In [207]:
train_data_input.to_csv('./Data/traininput.csv')
target_variable.to_csv('./Data/targetvariable.csv')

In [208]:
test_data.to_csv('./Data/normalisedtest.csv')

In [209]:
train_data_input

,id,Feature 1,Feature 7,Feature 8,Feature 9,Feature 10,Feature 12,Feature 13,Feature 14,Feature 16,Feature 17,Feature 22,Feature 23,Feature 24,Feature 25,Feature 26
0,143728,0.100000,0,1,0,0,0,0,0,0,0,0.507692,0.233333,0.534715,0.519481,0.102556
1,52657,0.090909,0,0,0,0,0,1,0,1,0,0.600000,0.233333,0.506736,0.501499,0.101597
2,124407,0.554545,0,0,0,1,0,0,0,0,1,0.364103,0.366667,0.869430,0.828172,0.157827
3,45535,0.039394,0,1,0,0,0,0,0,0,0,0.482051,0.200000,0.456995,0.446553,0.087220
4,178894,0.212121,0,0,0,0,1,0,0,0,0,0.589744,0.333333,0.625907,0.607393,0.123323
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135496,34345,0.151515,1,0,0,0,0,0,0,0,1,0.574359,0.266667,0.585492,0.560440,0.113738
135497,9899,0.039394,0,0,0,0,1,0,0,0,0,0.538462,0.266667,0.459067,0.439560,0.088498
135498,142454,0.554545,0,0,0,0,1,0,0,0,0,0.389744,0.333333,0.868394,0.829171,0.158786
135499,129168,0.160606,0,1,0,0,0,0,0,0,0,0.569231,0.333333,0.587565,0.571429,0.115335
135500,10470,0.460606,0,1,0,0,0,0,0,1,0,0.466667,0.266667,0.794819,0.771229,0.150479

In [210]:

test_data = test_data.drop('Feature 2',axis = 1)
test_data = test_data.drop('Feature 3',axis = 1)
test_data = test_data.drop('Feature 4',axis = 1)
test_data = test_data.drop('Feature 5',axis = 1)
test_data = test_data.drop('Feature 6',axis = 1)
test_data = test_data.drop('Feature 11',axis = 1)
test_data = test_data.drop('Feature 15',axis = 1)
test_data = test_data.drop('Feature 18',axis = 1)
test_data = test_data.drop('Feature 19',axis = 1)
test_data = test_data.drop('Feature 20',axis = 1)
test_data = test_data.drop('Feature 21',axis = 1)
#test_data = test_data.drop('Feature 23',axis = 1)

In [191]:
test_data.to_csv('./Data/normalisedtest.csv')